### ISSUE TITLE
麻烦加个 <Icon> 使用 svg 的例子··

### ISSUE THREAD

**Issue by mizi-lin** [xiaohuoni/dva-umi-mobile#1]
~~ 如题

对 react 配置不熟··

**Comment by xiaohuoni** [comment]
不好意思，这阶段休息，过几天，我再看看

**Comment by xiaohuoni** [comment]
https://github.com/HeskeyBaozi/reduce-antd-icons-bundle-demo
忘记了，这里补充一个demo（捂脸，别打我）
